name: 'TF Visualizer Action'
description: 'See changes for Terraform in pull requests'
author: 'Fatih Tokus'
inputs:
  pull-request:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  github-token: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pull-request }}
    - ${{ inputs.github-token }}
branding:
  icon: "git-pull-request"
  color: "purple"
